dashboard/dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views

from users import users_views, users_api_views
from rest_framework import routers

from users.users_views import CustomTokenObtainPairView

router = routers.SimpleRouter()
router.register(r'categories', users_api_views.CategoryCurd, basename="categories")
router.register(r'subcategories', users_api_views.SubCategoryCurd, basename="subcategories")
router.register(r'industries', users_api_views.IndustryCurd, basename="industries")
router.register(r'interestarea', users_api_views.InterestAreaCurd, basename="interestarea")
router.register(r'taxcurd', users_api_views.TaxCurd, basename="taxcurd")
router.register(r'solutions', users_api_views.SolutionCurd, basename="solution")
router.register(r'fetchOrders', users_api_views.FetchOrders, basename="fetchOrders")

# urlpatterns = router.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('api/', include(router.urls)),
    
    path('api/token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', include('vora.urls', namespace='vora')),
    path('summernote/', include('django_summernote.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password/', users_views.change_password, name='change_password'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Vora Dashboard"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Dashboard"

dashboard/vora/urls.py
from django.urls import path,include
from vora import vora_views
from users import users_views, users_api_views
from django.contrib import admin
app_name = 'vora'
urlpatterns = [
  path('admin_base/', admin.site.urls),
    # added by raj
    path('api/register', users_api_views.RegisterUserAPIView.as_view()),
    path('api/update_register_data/<int:pk>/', users_api_views.update_register_dataUserAPIView.as_view()),
    path('api/checkEmailWithToken', users_api_views.checkEmailWithToken.as_view()),
    path('api/checkEmailWithSendMail', users_api_views.checkEmailWithSendMail.as_view()),
    path('api/changePassword/<int:pk>/', users_api_views.changePassword.as_view()),
    path('api/changeoldtonewPassword/<int:pk>/', users_api_views.changeoldtonewPassword.as_view()),
    path('api/update_verify_data/<int:pk>/', users_api_views.update_verify_dataUserAPIView.as_view()),
    
    # path('loginapi/', users_api_views.LoginView.as_view()),
    path('api/add-order-detail', users_api_views.CreateOrderAPIView.as_view()),
    path('api/send_mail', users_api_views.send_mail.as_view()),
path('api/active_project_email', users_api_views.active_project_email.as_view()),
path('api/draft_project_email', users_api_views.draft_project_email.as_view()),
path('api/new_project_email', users_api_views.new_project_email.as_view()),

path('api/confirm_send_mail', users_api_views.confirm_send_mail.as_view()),

    path('back/users/', users_views.users, name="users"),
    path('back/customers/', users_views.customers, name="customers"),
    path('back/inactiveCustomers/', users_views.customers, name="inactiveCustomers"),
    path('back/category/', users_views.category, name="category"),
    path('back/user_history/', users_views.login_history, name="login_history"),
    
    path('back/interest-area/', users_views.interest_area, name="interest-area"),
    path('back/industry-filter/', users_views.industry_filter, name="industry-filter"),
    path('back/sub-category/', users_views.sub_category, name="sub-category"),
    path('back/solutions/', users_views.solutions, name="solutions"),
    path('back/all-orders/', users_views.all_orders, name="all-orders"),
    path('back/all-active-orders/', users_views.active_orders, name="all-active-orders"),
    path('back/all-draft-orders/', users_views.draft_orders, name="all-draft-orders"),
    path('back/all-complete-orders/', users_views.complete_orders, name="all-complete-orders"),
    
    path('back/view-order-detail/<int:id>/', users_views.view_order_solution, name="view-order-detail"),
    path('back/view-customer-detail/<int:id>/', users_views.view_customer, name="view-customer-detail"),
    path('back/archieved-solutions/', users_views.archieved_solutions, name="archieved-solutions"),
    path('back/tax/', users_views.tax, name="tax"),

    path('back/user-details/<int:id>/', users_views.user_details, name="user-details"),
    path('back/add-user/', users_views.add_user, name="add-user"),
    path('back/add-category/', users_views.add_category, name="add-category"),

    path('back/add-interest-area/', users_views.add_interest_area, name="add-interest-area"),

    path('back/add-industry-filter/', users_views.add_industry_filter, name="add-industry-filter"),

    path('back/add-solution/', users_views.add_solution, name="add-solution"),

    path('back/add-tax/', users_views.add_tax, name="add-tax"),

    path('back/add-sub-category/', users_views.add_sub_category, name="add-sub-category"),

    path('back/edit-user/<int:id>/', users_views.edit_user, name="edit-user"),
    path('back/edit-solution/<int:id>/', users_views.edit_solution, name="edit-solution"),
    path('back/edit-category/<int:id>/', users_views.edit_category, name="edit-category"),

    path('back/edit-interest-area/<int:id>/', users_views.edit_interest_area, name="edit-interest-area"),

    path('back/edit-sub-category/<int:id>/', users_views.edit_sub_category, name="edit-sub-category"),
    path('back/edit-tax/<int:id>/', users_views.edit_tax, name="edit-tax"),
    path('back/edit-industry-filter/<int:id>/', users_views.edit_industry_filter, name="edit-industry-filter"),

    path('back/delete-user/<int:id>/', users_views.delete_user, name="delete-user"),
    path('back/delete-multiple-user/', users_views.delete_multiple_user, name="delete-multiple-user"),

    path('back/delete-solution/<int:id>/', users_views.delete_solution, name="delete-solution"),
    path('back/change-order-status/<int:id>/', users_views.change_order_status, name="change-order-status"),
    path('back/active-multiple-solution/', users_views.active_multiple_solution, name="active-multiple-solution"),
    path('back/delete-category/<int:id>/', users_views.delete_category, name="delete-category"),
    path('back/delete-industry-filter/<int:id>/', users_views.delete_industry_filter, name="delete-industry-filter"),

    path('back/delete-interest-area/<int:id>/', users_views.delete_interest_area, name="delete-interest-area"),

    path('back/delete-sub-category/<int:id>/', users_views.delete_sub_category, name="delete-sub-category"),
    path('back/delete-tax/<int:id>/', users_views.delete_tax, name="delete-tax"),

    path('back/delete-multiple-category/', users_views.delete_multiple_category, name="delete-multiple-category"),
    path('back/delete-multiple-industry-filter/', users_views.delete_multiple_industry_filter,
         name="delete-multiple-industry-filter"),

    path('back/delete-multiple-interest-area/', users_views.delete_multiple_interest_area,
         name="delete-multiple-interest-area"),

    path('delete-multiple-sub-category/', users_views.delete_multiple_sub_category,
         name="delete-multiple-sub-category"),
    path('delete-multiple-tax/', users_views.delete_multiple_tax, name="delete-multiple-tax"),

    path('admin_login/', users_views.login_user, name="login"),
    path('back/logout/', users_views.logout_user, name="logout"),
    path('back/groups/', users_views.groups_list, name="groups"),
    path('back/group-edit/<int:id>/', users_views.group_edit, name="group-edit"),
    path('back/group-delete/<int:id>/', users_views.group_delete, name="group-delete"),
    path('back/group-add/', users_views.group_add, name="group-add"),
    path('back/permissions/', users_views.permissions, name="permissions"),
    path('back/edit-permissions/<int:id>/', users_views.edit_permissions, name="edit-permissions"),
    path('back/delete-permissions/<int:id>/', users_views.delete_permissions, name="delete-permissions"),
    path('back/assign-permissions-to-user/<int:id>/', users_views.assign_permissions_to_user,
         name="assign-permissions-to-user"),
    path('back/signup/', users_views.signup, name="signup"),
    path('back/activate/<uidb64>/<token>/', users_views.activate, name='activate'),

#    path('', vora_views.index, name="index"),
    path('back/index/', vora_views.index, name="index"),
    path('back/index_2/', vora_views.index_2, name="index_2"),
    path('back/projects/', vora_views.projects, name="projects"),
    path('back/contacts/', vora_views.contacts, name="contacts"),
    path('back/kanban/', vora_views.kanban, name="kanban"),

    path('back/calendar/', vora_views.calendar, name="calendar"),
    path('back/messages/', vora_views.messages, name="messages"),

    path('back/app-profile/', vora_views.app_profile, name="app-profile"),
    path('back/post-details/', vora_views.post_details, name="post-details"),
    path('back/email-compose/', vora_views.email_compose, name="email-compose"),
    path('back/email-inbox/', vora_views.email_inbox, name="email-inbox"),
    path('back/email-read/', vora_views.email_read, name="email-read"),
    path('back/app-calender/', vora_views.app_calender, name="app-calender"),
    path('back/ecom-product-grid/', vora_views.ecom_product_grid, name="ecom-product-grid"),
    path('back/ecom-product-list/', vora_views.ecom_product_list, name="ecom-product-list"),
    path('back/ecom-product-detail/', vora_views.ecom_product_detail, name="ecom-product-detail"),
    path('back/ecom-product-order/', vora_views.ecom_product_order, name="ecom-product-order"),
    path('back/ecom-checkout/', vora_views.ecom_checkout, name="ecom-checkout"),
    path('back/ecom-invoice/', vora_views.ecom_invoice, name="ecom-invoice"),
    path('back/ecom-customers/', vora_views.ecom_customers, name="ecom-customers"),
    path('back/chart-flot/', vora_views.chart_flot, name="chart-flot"),
    path('back/chart-morris/', vora_views.chart_morris, name="chart-morris"),
    path('back/chart-chartjs/', vora_views.chart_chartjs, name="chart-chartjs"),
    path('back/chart-chartist/', vora_views.chart_chartist, name="chart-chartist"),
    path('back/chart-sparkline/', vora_views.chart_sparkline, name="chart-sparkline"),
    path('back/chart-peity/', vora_views.chart_peity, name="chart-peity"),

    path('back/ui-accordion/', vora_views.ui_accordion, name="ui-accordion"),
    path('back/ui-alert/', vora_views.ui_alert, name="ui-alert"),
    path('back/ui-badge/', vora_views.ui_badge, name="ui-badge"),
    path('back/ui-button/', vora_views.ui_button, name="ui-button"),
    path('back/ui-modal/', vora_views.ui_modal, name="ui-modal"),
    path('back/ui-button-group/', vora_views.ui_button_group, name="ui-button-group"),
    path('back/ui-list-group/', vora_views.ui_list_group, name="ui-list-group"),
    path('back/ui-media-object/', vora_views.ui_media_object, name="ui-media-object"),
    path('back/ui-card/', vora_views.ui_card, name="ui-card"),
    path('back/ui-carousel/', vora_views.ui_carousel, name="ui-carousel"),
    path('back/ui-dropdown/', vora_views.ui_dropdown, name="ui-dropdown"),
    path('back/ui-popover/', vora_views.ui_popover, name="ui-popover"),
    path('back/ui-progressbar/', vora_views.ui_progressbar, name="ui-progressbar"),
    path('back/ui-tab/', vora_views.ui_tab, name="ui-tab"),
    path('back/ui-typography/', vora_views.ui_typography, name="ui-typography"),

dashboard/templates/vora/apps/shop/ecom-invoice.html
{% extends 'vora/elements/layouts/admin.html' %}
{% load static %}

<!-- Additional Css -->
{% block additional_css  %}

{% endblock %}


{% block content %}


        <div class="page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Layout</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Blank</a></li>
            </ol>
        </div>
        <div class="row">
            <div class="col-lg-12">

                <div class="card mt-3">
                    <div class="card-header"> Invoice <strong>01/01/2022</strong> <span class="float-right">
                            <strong>Status:</strong> Pending</span> </div>
                    <div class="card-body">
                        <div class="row mb-5">
                            <div class="mt-4 col-xl-3 col-lg-3 col-md-6 col-sm-6">
                                <h6>From:</h6>
                                <div> <strong>Webz Poland</strong> </div>
                                <div>Madalinskiego 8</div>
                                <div>71-101 Szczecin, Poland</div>
                                <div>Email: info@webz.com.pl</div>
                                <div>Phone: +48 444 666 3333</div>
                            </div>
                            <div class="mt-4 col-xl-3 col-lg-3 col-md-6 col-sm-6">
                                <h6>To:</h6>
                                <div> <strong>Bob Mart</strong> </div>
                                <div>Attn: Daniel Marek</div>
                                <div>43-190 Mikolow, Poland</div>
                                <div>Email: marek@daniel.com</div>
                                <div>Phone: +48 123 456 789</div>
                            </div>
                            <div class="mt-4 col-xl-6 col-lg-6 col-md-12 col-sm-12 d-flex justify-content-lg-end justify-content-md-center justify-content-xs-start">
                                <div class="row align-items-center">
                                    <div class="col-sm-9"> 
                                        <div class="brand-logo mb-3">
                                            <img class="logo-abbr me-2" src="{% static 'vora/images/logo.png' %}" alt="">
                                            <img class="logo-compact" src="{% static 'vora/images/logo-text.png' %}" alt="">
                                        </div>
                                        <span>Please send exact amount: <strong class="d-block">0.15050000 BTC</strong>
                                            <strong>1DonateWffyhwAjskoEwXt83pHZxhLTr8H</strong></span><br>
                                        <small class="text-muted">Current exchange rate 1BTC = $6590 USD</small>
                                    </div>
                                    <div class="col-sm-3 mt-3"> <img src="{% static 'vora/images/qr.png' %}" class="img-fluid width110"> </div>
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th class="center">#</th>
                                        <th>Item</th>
                                        <th>Description</th>
                                        <th class="right">Unit Cost</th>
                                        <th class="center">Qty</th>
                                        <th class="right">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="center">1</td>
                                        <td class="left strong">Origin License</td>
                                        <td class="left">Extended License</td>
                                        <td class="right">$999,00</td>
                                        <td class="center">1</td>
                                        <td class="right">$999,00</td>
                                    </tr>
                                    <tr>
                                        <td class="center">2</td>
                                        <td class="left">Custom Services</td>
                                        <td class="left">Instalation and Customization (cost per hour)</td>
                                        <td class="right">$150,00</td>
                                        <td class="center">20</td>
                                        <td class="right">$3.000,00</td>
                                    </tr>
                                    <tr>
                                        <td class="center">3</td>
                                        <td class="left">Hosting</td>
                                        <td class="left">1 year subcription</td>
                                        <td class="right">$499,00</td>
                                        <td class="center">1</td>
                                        <td class="right">$499,00</td>
                                    </tr>
                                    <tr>
                                        <td class="center">4</td>
                                        <td class="left">Platinum Support</td>
                                        <td class="left">1 year subcription 24/7</td>
                                        <td class="right">$3.999,00</td>
                                        <td class="center">1</td>
                                        <td class="right">$3.999,00</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-lg-4 col-sm-5"> </div>
                            <div class="col-lg-4 col-sm-5 ms-auto">
                                <table class="table table-clear">
                                    <tbody>
                                        <tr>
                                            <td class="left"><strong>Subtotal</strong></td>
                                            <td class="right">$8.497,00</td>
                                        </tr>
                                        <tr>
                                            <td class="left"><strong>Discount (20%)</strong></td>
                                            <td class="right">$1,699,40</td>
                                        </tr>
                                        <tr>
                                            <td class="left"><strong>VAT (10%)</strong></td>
                                            <td class="right">$679,76</td>
                                        </tr>
                                        <tr>
                                            <td class="left"><strong>Total</strong></td>
                                            <td class="right"><strong>$7.477,36</strong><br>
                                                <strong>0.15050000 BTC</strong></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

{% block additional_js  %}

{% endblock %}

dashboard/templates/vora/apps/shop/ecom-product-grid.html
{% extends 'vora/elements/layouts/admin.html' %}
{% load static %}


{% block additional_css  %}
{% endblock %}

{% block content %}


        <div class="page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Layout</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Blank</a></li>
            </ol>
        </div>
        <div class="row">
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="new-arrival-product">
                            <div class="new-arrivals-img-contnent">
                                <img class="img-fluid" src="{% static 'vora/images/product/1.jpg' %}" alt="">
                            </div>
                            <div class="new-arrival-content text-center mt-3">
                                <h4><a href="{% url 'vora:ecom-product-detail' %}">Bonorum et Malorum</a></h4>
                                <ul class="star-rating">
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star-half-empty"></i></li>
                                    <li><i class="fa fa-star-half-empty"></i></li>
                                </ul>
                                <span class="price">$761.00</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="new-arrival-product">
                            <div class="new-arrivals-img-contnent">
                                <img class="img-fluid" src="{% static 'vora/images/product/2.jpg' %}" alt="">
                            </div>
                            <div class="new-arrival-content text-center mt-3">
                                <h4><a href="{% url 'vora:ecom-product-detail' %}">Striped Dress</a></h4>
                                <ul class="star-rating">
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                </ul>
                                <span class="price">$159.00</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="new-arrival-product">
                            <div class="new-arrivals-img-contnent">
                                <img class="img-fluid" src="{% static 'vora/images/product/3.jpg' %}" alt="">
                            </div>
                            <div class="new-arrival-content text-center mt-3">
                                <h4><a href="{% url 'vora:ecom-product-detail' %}">BBow polka-dot</a></h4>
                                <ul class="star-rating">
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                </ul>
                                <span class="price">$357.00</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="new-arrival-product">
                            <div class="new-arrivals-img-contnent">
                                <img class="img-fluid" src="{% static 'vora/images/product/4.jpg' %}" alt="">
                            </div>
                            <div class="new-arrival-content text-center mt-3">
                                <h4><a href="{% url 'vora:ecom-product-detail' %}">Z Product 360</a></h4>
                                <ul class="star-rating">
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star-half-empty"></i></li>
                                    <li><i class="fa fa-star-half-empty"></i></li>
                                </ul>
                                <span class="price">$654.00</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="new-arrival-product">
                            <div class="new-arrivals-img-contnent">
                                <img class="img-fluid" src="{% static 'vora/images/product/5.jpg' %}" alt="">
                            </div>
                            <div class="new-arrival-content text-center mt-3">
                                <h4><a href="{% url 'vora:ecom-product-detail' %}">Chair Grey</a></h4>
                                <ul class="star-rating">
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                </ul>
                                <span class="price">$369.00</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="new-arrival-product">
                            <div class="new-arrivals-img-contnent">
                                <img class="img-fluid" src="{% static 'vora/images/product/6.jpg' %}" alt="">
                            </div>
                            <div class="new-arrival-content text-center mt-3">
                                <h4><a href="{% url 'vora:ecom-product-detail' %}">fox sake withe</a></h4>
                                <ul class="star-rating">
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                </ul>
                                <span class="price">$245.00</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="new-arrival-product">
                            <div class="new-arrivals-img-contnent">
                                <img class="img-fluid" src="{% static 'vora/images/product/7.jpg' %}" alt="">
                            </div>
                            <div class="new-arrival-content text-center mt-3">
                                <h4><a href="{% url 'vora:ecom-product-detail' %}">Back Bag</a></h4>
                                <ul class="star-rating">
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                </ul>
                                <span class="price">$364.00</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="new-arrival-product">
                            <div class="new-arrivals-img-contnent">
                                <img class="img-fluid" src="{% static 'vora/images/product/1.jpg' %}" alt="">
                            </div>
                            <div class="new-arrival-content text-center mt-3">
                                <h4><a href="{% url 'vora:ecom-product-detail' %}">FLARE DRESS</a></h4>
                                <ul class="star-rating">
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star-half-empty"></i></li>
                                    <li><i class="fa fa-star-half-empty"></i></li>
                                </ul>
                                <span class="price">$548.00</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

{% block additional_js  %}
{% endblock %}