dashboard/dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views

from users import users_views, users_api_views
from rest_framework import routers

from users.users_views import CustomTokenObtainPairView

router = routers.SimpleRouter()
router.register(r'categories', users_api_views.CategoryCurd, basename="categories")
router.register(r'subcategories', users_api_views.SubCategoryCurd, basename="subcategories")
router.register(r'industries', users_api_views.IndustryCurd, basename="industries")
router.register(r'interestarea', users_api_views.InterestAreaCurd, basename="interestarea")
router.register(r'taxcurd', users_api_views.TaxCurd, basename="taxcurd")
router.register(r'solutions', users_api_views.SolutionCurd, basename="solution")
router.register(r'fetchOrders', users_api_views.FetchOrders, basename="fetchOrders")

# urlpatterns = router.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('api/', include(router.urls)),
    
    path('api/token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', include('vora.urls', namespace='vora')),
    path('summernote/', include('django_summernote.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password/', users_views.change_password, name='change_password'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Vora Dashboard"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Dashboard"

dashboard/vora/urls.py
from django.urls import path,include
from vora import vora_views
from users import users_views, users_api_views
from django.contrib import admin
app_name = 'vora'
urlpatterns = [
  path('admin_base/', admin.site.urls),
    # added by raj
    path('api/register', users_api_views.RegisterUserAPIView.as_view()),
    path('api/update_register_data/<int:pk>/', users_api_views.update_register_dataUserAPIView.as_view()),
    path('api/checkEmailWithToken', users_api_views.checkEmailWithToken.as_view()),
    path('api/checkEmailWithSendMail', users_api_views.checkEmailWithSendMail.as_view()),
    path('api/changePassword/<int:pk>/', users_api_views.changePassword.as_view()),
    path('api/changeoldtonewPassword/<int:pk>/', users_api_views.changeoldtonewPassword.as_view()),
    path('api/update_verify_data/<int:pk>/', users_api_views.update_verify_dataUserAPIView.as_view()),
    
    # path('loginapi/', users_api_views.LoginView.as_view()),
    path('api/add-order-detail', users_api_views.CreateOrderAPIView.as_view()),
    path('api/send_mail', users_api_views.send_mail.as_view()),
path('api/active_project_email', users_api_views.active_project_email.as_view()),
path('api/draft_project_email', users_api_views.draft_project_email.as_view()),
path('api/new_project_email', users_api_views.new_project_email.as_view()),

path('api/confirm_send_mail', users_api_views.confirm_send_mail.as_view()),

    path('back/users/', users_views.users, name="users"),
    path('back/customers/', users_views.customers, name="customers"),
    path('back/inactiveCustomers/', users_views.customers, name="inactiveCustomers"),
    path('back/category/', users_views.category, name="category"),
    path('back/user_history/', users_views.login_history, name="login_history"),
    
    path('back/interest-area/', users_views.interest_area, name="interest-area"),
    path('back/industry-filter/', users_views.industry_filter, name="industry-filter"),
    path('back/sub-category/', users_views.sub_category, name="sub-category"),
    path('back/solutions/', users_views.solutions, name="solutions"),
    path('back/all-orders/', users_views.all_orders, name="all-orders"),
    path('back/all-active-orders/', users_views.active_orders, name="all-active-orders"),
    path('back/all-draft-orders/', users_views.draft_orders, name="all-draft-orders"),
    path('back/all-complete-orders/', users_views.complete_orders, name="all-complete-orders"),
    
    path('back/view-order-detail/<int:id>/', users_views.view_order_solution, name="view-order-detail"),
    path('back/view-customer-detail/<int:id>/', users_views.view_customer, name="view-customer-detail"),
    path('back/archieved-solutions/', users_views.archieved_solutions, name="archieved-solutions"),
    path('back/tax/', users_views.tax, name="tax"),

    path('back/user-details/<int:id>/', users_views.user_details, name="user-details"),
    path('back/add-user/', users_views.add_user, name="add-user"),
    path('back/add-category/', users_views.add_category, name="add-category"),

    path('back/add-interest-area/', users_views.add_interest_area, name="add-interest-area"),

    path('back/add-industry-filter/', users_views.add_industry_filter, name="add-industry-filter"),

    path('back/add-solution/', users_views.add_solution, name="add-solution"),

    path('back/add-tax/', users_views.add_tax, name="add-tax"),

    path('back/add-sub-category/', users_views.add_sub_category, name="add-sub-category"),

    path('back/edit-user/<int:id>/', users_views.edit_user, name="edit-user"),
    path('back/edit-solution/<int:id>/', users_views.edit_solution, name="edit-solution"),
    path('back/edit-category/<int:id>/', users_views.edit_category, name="edit-category"),

    path('back/edit-interest-area/<int:id>/', users_views.edit_interest_area, name="edit-interest-area"),

    path('back/edit-sub-category/<int:id>/', users_views.edit_sub_category, name="edit-sub-category"),
    path('back/edit-tax/<int:id>/', users_views.edit_tax, name="edit-tax"),
    path('back/edit-industry-filter/<int:id>/', users_views.edit_industry_filter, name="edit-industry-filter"),

    path('back/delete-user/<int:id>/', users_views.delete_user, name="delete-user"),
    path('back/delete-multiple-user/', users_views.delete_multiple_user, name="delete-multiple-user"),

    path('back/delete-solution/<int:id>/', users_views.delete_solution, name="delete-solution"),
    path('back/change-order-status/<int:id>/', users_views.change_order_status, name="change-order-status"),
    path('back/active-multiple-solution/', users_views.active_multiple_solution, name="active-multiple-solution"),
    path('back/delete-category/<int:id>/', users_views.delete_category, name="delete-category"),
    path('back/delete-industry-filter/<int:id>/', users_views.delete_industry_filter, name="delete-industry-filter"),

    path('back/delete-interest-area/<int:id>/', users_views.delete_interest_area, name="delete-interest-area"),

    path('back/delete-sub-category/<int:id>/', users_views.delete_sub_category, name="delete-sub-category"),
    path('back/delete-tax/<int:id>/', users_views.delete_tax, name="delete-tax"),

    path('back/delete-multiple-category/', users_views.delete_multiple_category, name="delete-multiple-category"),
    path('back/delete-multiple-industry-filter/', users_views.delete_multiple_industry_filter,
         name="delete-multiple-industry-filter"),

    path('back/delete-multiple-interest-area/', users_views.delete_multiple_interest_area,
         name="delete-multiple-interest-area"),

    path('delete-multiple-sub-category/', users_views.delete_multiple_sub_category,
         name="delete-multiple-sub-category"),
    path('delete-multiple-tax/', users_views.delete_multiple_tax, name="delete-multiple-tax"),

    path('admin_login/', users_views.login_user, name="login"),
    path('back/logout/', users_views.logout_user, name="logout"),
    path('back/groups/', users_views.groups_list, name="groups"),
    path('back/group-edit/<int:id>/', users_views.group_edit, name="group-edit"),
    path('back/group-delete/<int:id>/', users_views.group_delete, name="group-delete"),
    path('back/group-add/', users_views.group_add, name="group-add"),
    path('back/permissions/', users_views.permissions, name="permissions"),
    path('back/edit-permissions/<int:id>/', users_views.edit_permissions, name="edit-permissions"),
    path('back/delete-permissions/<int:id>/', users_views.delete_permissions, name="delete-permissions"),
    path('back/assign-permissions-to-user/<int:id>/', users_views.assign_permissions_to_user,
         name="assign-permissions-to-user"),
    path('back/signup/', users_views.signup, name="signup"),
    path('back/activate/<uidb64>/<token>/', users_views.activate, name='activate'),

#    path('', vora_views.index, name="index"),
    path('back/index/', vora_views.index, name="index"),
    path('back/index_2/', vora_views.index_2, name="index_2"),
    path('back/projects/', vora_views.projects, name="projects"),
    path('back/contacts/', vora_views.contacts, name="contacts"),
    path('back/kanban/', vora_views.kanban, name="kanban"),

    path('back/calendar/', vora_views.calendar, name="calendar"),
    path('back/messages/', vora_views.messages, name="messages"),

    path('back/app-profile/', vora_views.app_profile, name="app-profile"),
    path('back/post-details/', vora_views.post_details, name="post-details"),
    path('back/email-compose/', vora_views.email_compose, name="email-compose"),
    path('back/email-inbox/', vora_views.email_inbox, name="email-inbox"),
    path('back/email-read/', vora_views.email_read, name="email-read"),
    path('back/app-calender/', vora_views.app_calender, name="app-calender"),
    path('back/ecom-product-grid/', vora_views.ecom_product_grid, name="ecom-product-grid"),
    path('back/ecom-product-list/', vora_views.ecom_product_list, name="ecom-product-list"),
    path('back/ecom-product-detail/', vora_views.ecom_product_detail, name="ecom-product-detail"),
    path('back/ecom-product-order/', vora_views.ecom_product_order, name="ecom-product-order"),
    path('back/ecom-checkout/', vora_views.ecom_checkout, name="ecom-checkout"),
    path('back/ecom-invoice/', vora_views.ecom_invoice, name="ecom-invoice"),
    path('back/ecom-customers/', vora_views.ecom_customers, name="ecom-customers"),
    path('back/chart-flot/', vora_views.chart_flot, name="chart-flot"),
    path('back/chart-morris/', vora_views.chart_morris, name="chart-morris"),
    path('back/chart-chartjs/', vora_views.chart_chartjs, name="chart-chartjs"),
    path('back/chart-chartist/', vora_views.chart_chartist, name="chart-chartist"),
    path('back/chart-sparkline/', vora_views.chart_sparkline, name="chart-sparkline"),
    path('back/chart-peity/', vora_views.chart_peity, name="chart-peity"),

    path('back/ui-accordion/', vora_views.ui_accordion, name="ui-accordion"),
    path('back/ui-alert/', vora_views.ui_alert, name="ui-alert"),
    path('back/ui-badge/', vora_views.ui_badge, name="ui-badge"),
    path('back/ui-button/', vora_views.ui_button, name="ui-button"),
    path('back/ui-modal/', vora_views.ui_modal, name="ui-modal"),
    path('back/ui-button-group/', vora_views.ui_button_group, name="ui-button-group"),
    path('back/ui-list-group/', vora_views.ui_list_group, name="ui-list-group"),
    path('back/ui-media-object/', vora_views.ui_media_object, name="ui-media-object"),
    path('back/ui-card/', vora_views.ui_card, name="ui-card"),
    path('back/ui-carousel/', vora_views.ui_carousel, name="ui-carousel"),
    path('back/ui-dropdown/', vora_views.ui_dropdown, name="ui-dropdown"),
    path('back/ui-popover/', vora_views.ui_popover, name="ui-popover"),
    path('back/ui-progressbar/', vora_views.ui_progressbar, name="ui-progressbar"),
    path('back/ui-tab/', vora_views.ui_tab, name="ui-tab"),
    path('back/ui-typography/', vora_views.ui_typography, name="ui-typography"),

dashboard/vora/models.py
from django.db import models

# Create your models here.

dashboard/vora/views.py
from django.shortcuts import render

# Create your views here.

dashboard/templates/vora/calendar.html
{% extends 'vora/elements/layouts/admin.html' %}
{% load static %}

{% block additional_css %}
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-xl-9 col-xxl-8">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <div id="calendar" class="app-fullcalendar dashboard-calendar"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-xxl-4">
        <div class="row">
            <div class="col-xl-12">
                <div class="card bg-primary">
                    <div class="card-body">
                        <div class="date-bx d-flex align-items-center">
                            <h2 class="mb-0 me-3">26</h2>
                            <div>
                                <p class="mb-0 text-white op7">Today</p>
                                <span class="fs-24 text-white font-w600">Sunday</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header border-0 shadow-sm">
                        <h4 class="fs-20 text-black font-w600">Project Today</h4>
                    </div>
                    <div class="card-body">
                        <div class="media pb-3 mb-3 border-bottom">
                            <span class="p-3 me-3 border border-primary rounded-circle">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M22.9479 9.32202C22.8893 9.14733 22.7836 8.99223 22.6424 8.87382C22.5013 8.75541 22.3301 8.67831 22.1479 8.65102L15.7659 7.67602L12.9019 1.57602C12.8211 1.40423 12.6931 1.25896 12.5329 1.15722C12.3726 1.05547 12.1867 1.00143 11.9969 1.00143C11.8071 1.00143 11.6212 1.05547 11.4609 1.15722C11.3006 1.25896 11.1726 1.40423 11.0919 1.57602L8.22789 7.67602L1.84589 8.65102C1.66411 8.67873 1.49349 8.75602 1.35279 8.8744C1.21209 8.99278 1.10675 9.14767 1.04835 9.32203C0.989954 9.49639 0.980764 9.68347 1.02179 9.86272C1.06282 10.042 1.15247 10.2064 1.28089 10.338L5.93189 15.1L4.83189 21.838C4.80187 22.0229 4.8244 22.2126 4.89691 22.3853C4.96942 22.558 5.08899 22.7069 5.242 22.815C5.39502 22.9231 5.57531 22.986 5.76235 22.9967C5.94939 23.0073 6.13564 22.9651 6.29989 22.875L11.9999 19.727L17.6999 22.875C17.8641 22.9659 18.0506 23.0087 18.2381 22.9985C18.4255 22.9883 18.6063 22.9256 18.7597 22.8176C18.9132 22.7095 19.0331 22.5604 19.1059 22.3873C19.1786 22.2143 19.2011 22.0243 19.1709 21.839L18.0709 15.101L22.7189 10.338C22.8467 10.2061 22.9357 10.0414 22.9761 9.86219C23.0165 9.68296 23.0067 9.49607 22.9479 9.32202Z" fill="#2953E8"/>
                                </svg>
                            </span>
                            <div class="media-body">
                                <p class="fs-14 mb-2">09:30 AM - 11:00 AM</p>
                                <h6 class="fs-16 font-w600"><a href="{% url 'vora:projects' %}" class="text-black">Convert Apps to mobile version</a></h6>
                                <ul class="users">
                                    <li><img src="{% static 'vora/images/users/9.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'vora/images/users/10.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'vora/images/users/11.jpg' %}" alt=""></li>
                                </ul>
                            </div>
                        </div>
                        <div class="media pb-3 mb-3 border-bottom">
                            <span class="p-3 me-3 border border-success rounded-circle">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M22.9479 9.32202C22.8893 9.14733 22.7836 8.99223 22.6424 8.87382C22.5013 8.75541 22.3301 8.67831 22.1479 8.65102L15.7659 7.67602L12.9019 1.57602C12.8211 1.40423 12.6931 1.25896 12.5329 1.15722C12.3726 1.05547 12.1867 1.00143 11.9969 1.00143C11.8071 1.00143 11.6212 1.05547 11.4609 1.15722C11.3006 1.25896 11.1726 1.40423 11.0919 1.57602L8.22789 7.67602L1.84589 8.65102C1.66411 8.67873 1.49349 8.75602 1.35279 8.8744C1.21209 8.99278 1.10675 9.14767 1.04835 9.32203C0.989954 9.49639 0.980764 9.68347 1.02179 9.86272C1.06282 10.042 1.15247 10.2064 1.28089 10.338L5.93189 15.1L4.83189 21.838C4.80187 22.0229 4.8244 22.2126 4.89691 22.3853C4.96942 22.558 5.08899 22.7069 5.242 22.815C5.39502 22.9231 5.57531 22.986 5.76235 22.9967C5.94939 23.0073 6.13564 22.9651 6.29989 22.875L11.9999 19.727L17.6999 22.875C17.8641 22.9659 18.0506 23.0087 18.2381 22.9985C18.4255 22.9883 18.6063 22.9256 18.7597 22.8176C18.9132 22.7095 19.0331 22.5604 19.1059 22.3873C19.1786 22.2143 19.2011 22.0243 19.1709 21.839L18.0709 15.101L22.7189 10.338C22.8467 10.2061 22.9357 10.0414 22.9761 9.86219C23.0165 9.68296 23.0067 9.49607 22.9479 9.32202Z" fill="#39D952"/>
                                </svg>
                            </span>
                            <div class="media-body">
                                <p class="fs-14 mb-2">09:30 AM - 11:00 AM</p>
                                <h6 class="fs-16 font-w600"><a href="{% url 'vora:projects' %}" class="text-black">Weekly Meetings for Vora App</a></h6>
                                <ul class="users">
                                    <li><img src="{% static 'vora/images/users/9.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'vora/images/users/10.jpg' %}" alt=""></li>
                                </ul>
                            </div>
                        </div>
                        <div class="media">
                            <span class="p-3 me-3 border border-warning rounded-circle">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M22.9479 9.32202C22.8893 9.14733 22.7836 8.99223 22.6424 8.87382C22.5013 8.75541 22.3301 8.67831 22.1479 8.65102L15.7659 7.67602L12.9019 1.57602C12.8211 1.40423 12.6931 1.25896 12.5329 1.15722C12.3726 1.05547 12.1867 1.00143 11.9969 1.00143C11.8071 1.00143 11.6212 1.05547 11.4609 1.15722C11.3006 1.25896 11.1726 1.40423 11.0919 1.57602L8.22789 7.67602L1.84589 8.65102C1.66411 8.67873 1.49349 8.75602 1.35279 8.8744C1.21209 8.99278 1.10675 9.14767 1.04835 9.32203C0.989954 9.49639 0.980764 9.68347 1.02179 9.86272C1.06282 10.042 1.15247 10.2064 1.28089 10.338L5.93189 15.1L4.83189 21.838C4.80187 22.0229 4.8244 22.2126 4.89691 22.3853C4.96942 22.558 5.08899 22.7069 5.242 22.815C5.39502 22.9231 5.57531 22.986 5.76235 22.9967C5.94939 23.0073 6.13564 22.9651 6.29989 22.875L11.9999 19.727L17.6999 22.875C17.8641 22.9659 18.0506 23.0087 18.2381 22.9985C18.4255 22.9883 18.6063 22.9256 18.7597 22.8176C18.9132 22.7095 19.0331 22.5604 19.1059 22.3873C19.1786 22.2143 19.2011 22.0243 19.1709 21.839L18.0709 15.101L22.7189 10.338C22.8467 10.2061 22.9357 10.0414 22.9761 9.86219C23.0165 9.68296 23.0067 9.49607 22.9479 9.32202Z" fill="#FF6F1E"/>
                                </svg>
                            </span>
                            <div class="media-body">
                                <p class="fs-14 mb-2">09:30 AM - 11:00 AM</p>
                                <h6 class="fs-16 font-w600"><a href="{% url 'vora:projects' %}" class="text-black">Annual Meeting for Backand Vora App</a></h6>
                                <ul class="users">
                                    <li><img src="{% static 'vora/images/users/11.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'vora/images/users/9.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'vora/images/users/10.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'vora/images/users/11.jpg' %}" alt=""></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block additional_js %}

{% endblock %}