dashboard/dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views

from users import users_views, users_api_views
from rest_framework import routers

from users.users_views import CustomTokenObtainPairView

router = routers.SimpleRouter()
router.register(r'categories', users_api_views.CategoryCurd, basename="categories")
router.register(r'subcategories', users_api_views.SubCategoryCurd, basename="subcategories")
router.register(r'industries', users_api_views.IndustryCurd, basename="industries")
router.register(r'interestarea', users_api_views.InterestAreaCurd, basename="interestarea")
router.register(r'taxcurd', users_api_views.TaxCurd, basename="taxcurd")
router.register(r'solutions', users_api_views.SolutionCurd, basename="solution")
router.register(r'fetchOrders', users_api_views.FetchOrders, basename="fetchOrders")

# urlpatterns = router.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('api/', include(router.urls)),
    
    path('api/token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', include('vora.urls', namespace='vora')),
    path('summernote/', include('django_summernote.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password/', users_views.change_password, name='change_password'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Vora Dashboard"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Dashboard"

dashboard/vora/urls.py
from django.urls import path,include
from vora import vora_views
from users import users_views, users_api_views
from django.contrib import admin
app_name = 'vora'
urlpatterns = [
  path('admin_base/', admin.site.urls),
    # added by raj
    path('api/register', users_api_views.RegisterUserAPIView.as_view()),
    path('api/update_register_data/<int:pk>/', users_api_views.update_register_dataUserAPIView.as_view()),
    path('api/checkEmailWithToken', users_api_views.checkEmailWithToken.as_view()),
    path('api/checkEmailWithSendMail', users_api_views.checkEmailWithSendMail.as_view()),
    path('api/changePassword/<int:pk>/', users_api_views.changePassword.as_view()),
    path('api/changeoldtonewPassword/<int:pk>/', users_api_views.changeoldtonewPassword.as_view()),
    path('api/update_verify_data/<int:pk>/', users_api_views.update_verify_dataUserAPIView.as_view()),
    
    # path('loginapi/', users_api_views.LoginView.as_view()),
    path('api/add-order-detail', users_api_views.CreateOrderAPIView.as_view()),
    path('api/send_mail', users_api_views.send_mail.as_view()),
path('api/active_project_email', users_api_views.active_project_email.as_view()),
path('api/draft_project_email', users_api_views.draft_project_email.as_view()),
path('api/new_project_email', users_api_views.new_project_email.as_view()),

path('api/confirm_send_mail', users_api_views.confirm_send_mail.as_view()),

    path('back/users/', users_views.users, name="users"),
    path('back/customers/', users_views.customers, name="customers"),
    path('back/inactiveCustomers/', users_views.customers, name="inactiveCustomers"),
    path('back/category/', users_views.category, name="category"),
    path('back/user_history/', users_views.login_history, name="login_history"),
    
    path('back/interest-area/', users_views.interest_area, name="interest-area"),
    path('back/industry-filter/', users_views.industry_filter, name="industry-filter"),
    path('back/sub-category/', users_views.sub_category, name="sub-category"),
    path('back/solutions/', users_views.solutions, name="solutions"),
    path('back/all-orders/', users_views.all_orders, name="all-orders"),
    path('back/all-active-orders/', users_views.active_orders, name="all-active-orders"),
    path('back/all-draft-orders/', users_views.draft_orders, name="all-draft-orders"),
    path('back/all-complete-orders/', users_views.complete_orders, name="all-complete-orders"),
    
    path('back/view-order-detail/<int:id>/', users_views.view_order_solution, name="view-order-detail"),
    path('back/view-customer-detail/<int:id>/', users_views.view_customer, name="view-customer-detail"),
    path('back/archieved-solutions/', users_views.archieved_solutions, name="archieved-solutions"),
    path('back/tax/', users_views.tax, name="tax"),

    path('back/user-details/<int:id>/', users_views.user_details, name="user-details"),
    path('back/add-user/', users_views.add_user, name="add-user"),
    path('back/add-category/', users_views.add_category, name="add-category"),

    path('back/add-interest-area/', users_views.add_interest_area, name="add-interest-area"),

    path('back/add-industry-filter/', users_views.add_industry_filter, name="add-industry-filter"),

    path('back/add-solution/', users_views.add_solution, name="add-solution"),

    path('back/add-tax/', users_views.add_tax, name="add-tax"),

    path('back/add-sub-category/', users_views.add_sub_category, name="add-sub-category"),

    path('back/edit-user/<int:id>/', users_views.edit_user, name="edit-user"),
    path('back/edit-solution/<int:id>/', users_views.edit_solution, name="edit-solution"),
    path('back/edit-category/<int:id>/', users_views.edit_category, name="edit-category"),

    path('back/edit-interest-area/<int:id>/', users_views.edit_interest_area, name="edit-interest-area"),

    path('back/edit-sub-category/<int:id>/', users_views.edit_sub_category, name="edit-sub-category"),
    path('back/edit-tax/<int:id>/', users_views.edit_tax, name="edit-tax"),
    path('back/edit-industry-filter/<int:id>/', users_views.edit_industry_filter, name="edit-industry-filter"),

    path('back/delete-user/<int:id>/', users_views.delete_user, name="delete-user"),
    path('back/delete-multiple-user/', users_views.delete_multiple_user, name="delete-multiple-user"),

    path('back/delete-solution/<int:id>/', users_views.delete_solution, name="delete-solution"),
    path('back/change-order-status/<int:id>/', users_views.change_order_status, name="change-order-status"),
    path('back/active-multiple-solution/', users_views.active_multiple_solution, name="active-multiple-solution"),
    path('back/delete-category/<int:id>/', users_views.delete_category, name="delete-category"),
    path('back/delete-industry-filter/<int:id>/', users_views.delete_industry_filter, name="delete-industry-filter"),

    path('back/delete-interest-area/<int:id>/', users_views.delete_interest_area, name="delete-interest-area"),

    path('back/delete-sub-category/<int:id>/', users_views.delete_sub_category, name="delete-sub-category"),
    path('back/delete-tax/<int:id>/', users_views.delete_tax, name="delete-tax"),

    path('back/delete-multiple-category/', users_views.delete_multiple_category, name="delete-multiple-category"),
    path('back/delete-multiple-industry-filter/', users_views.delete_multiple_industry_filter,
         name="delete-multiple-industry-filter"),

    path('back/delete-multiple-interest-area/', users_views.delete_multiple_interest_area,
         name="delete-multiple-interest-area"),

    path('delete-multiple-sub-category/', users_views.delete_multiple_sub_category,
         name="delete-multiple-sub-category"),
    path('delete-multiple-tax/', users_views.delete_multiple_tax, name="delete-multiple-tax"),

    path('admin_login/', users_views.login_user, name="login"),
    path('back/logout/', users_views.logout_user, name="logout"),
    path('back/groups/', users_views.groups_list, name="groups"),
    path('back/group-edit/<int:id>/', users_views.group_edit, name="group-edit"),
    path('back/group-delete/<int:id>/', users_views.group_delete, name="group-delete"),
    path('back/group-add/', users_views.group_add, name="group-add"),
    path('back/permissions/', users_views.permissions, name="permissions"),
    path('back/edit-permissions/<int:id>/', users_views.edit_permissions, name="edit-permissions"),
    path('back/delete-permissions/<int:id>/', users_views.delete_permissions, name="delete-permissions"),
    path('back/assign-permissions-to-user/<int:id>/', users_views.assign_permissions_to_user,
         name="assign-permissions-to-user"),
    path('back/signup/', users_views.signup, name="signup"),
    path('back/activate/<uidb64>/<token>/', users_views.activate, name='activate'),

#    path('', vora_views.index, name="index"),
    path('back/index/', vora_views.index, name="index"),
    path('back/index_2/', vora_views.index_2, name="index_2"),
    path('back/projects/', vora_views.projects, name="projects"),
    path('back/contacts/', vora_views.contacts, name="contacts"),
    path('back/kanban/', vora_views.kanban, name="kanban"),

    path('back/calendar/', vora_views.calendar, name="calendar"),
    path('back/messages/', vora_views.messages, name="messages"),

    path('back/app-profile/', vora_views.app_profile, name="app-profile"),
    path('back/post-details/', vora_views.post_details, name="post-details"),
    path('back/email-compose/', vora_views.email_compose, name="email-compose"),
    path('back/email-inbox/', vora_views.email_inbox, name="email-inbox"),
    path('back/email-read/', vora_views.email_read, name="email-read"),
    path('back/app-calender/', vora_views.app_calender, name="app-calender"),
    path('back/ecom-product-grid/', vora_views.ecom_product_grid, name="ecom-product-grid"),
    path('back/ecom-product-list/', vora_views.ecom_product_list, name="ecom-product-list"),
    path('back/ecom-product-detail/', vora_views.ecom_product_detail, name="ecom-product-detail"),
    path('back/ecom-product-order/', vora_views.ecom_product_order, name="ecom-product-order"),
    path('back/ecom-checkout/', vora_views.ecom_checkout, name="ecom-checkout"),
    path('back/ecom-invoice/', vora_views.ecom_invoice, name="ecom-invoice"),
    path('back/ecom-customers/', vora_views.ecom_customers, name="ecom-customers"),
    path('back/chart-flot/', vora_views.chart_flot, name="chart-flot"),
    path('back/chart-morris/', vora_views.chart_morris, name="chart-morris"),
    path('back/chart-chartjs/', vora_views.chart_chartjs, name="chart-chartjs"),
    path('back/chart-chartist/', vora_views.chart_chartist, name="chart-chartist"),
    path('back/chart-sparkline/', vora_views.chart_sparkline, name="chart-sparkline"),
    path('back/chart-peity/', vora_views.chart_peity, name="chart-peity"),

    path('back/ui-accordion/', vora_views.ui_accordion, name="ui-accordion"),
    path('back/ui-alert/', vora_views.ui_alert, name="ui-alert"),
    path('back/ui-badge/', vora_views.ui_badge, name="ui-badge"),
    path('back/ui-button/', vora_views.ui_button, name="ui-button"),
    path('back/ui-modal/', vora_views.ui_modal, name="ui-modal"),
    path('back/ui-button-group/', vora_views.ui_button_group, name="ui-button-group"),
    path('back/ui-list-group/', vora_views.ui_list_group, name="ui-list-group"),
    path('back/ui-media-object/', vora_views.ui_media_object, name="ui-media-object"),
    path('back/ui-card/', vora_views.ui_card, name="ui-card"),
    path('back/ui-carousel/', vora_views.ui_carousel, name="ui-carousel"),
    path('back/ui-dropdown/', vora_views.ui_dropdown, name="ui-dropdown"),
    path('back/ui-popover/', vora_views.ui_popover, name="ui-popover"),
    path('back/ui-progressbar/', vora_views.ui_progressbar, name="ui-progressbar"),
    path('back/ui-tab/', vora_views.ui_tab, name="ui-tab"),
    path('back/ui-typography/', vora_views.ui_typography, name="ui-typography"),

dashboard/vora/models.py
from django.db import models

# Create your models here.

dashboard/vora/views.py
from django.shortcuts import render

# Create your views here.

dashboard/templates/vora/elements/footer.html
{% load static %}
<div class="footer">
    <div class="copyright">
        <p>Copyright © Designed &amp; Developed by <a href="https://www.budventure.technology/" target="_blank">Budventure Technologies</a> 2023</p>
    </div>
</div>

dashboard/templates/vora/elements/header.html
{% load static %}
<div class="header">
    <div class="header-content">
        <nav class="navbar navbar-expand">
            <div class="collapse navbar-collapse justify-content-between">
                <div class="header-left">
                    <div class="dashboard_bar">
                        {{ page_title }}
                    </div>
                </div>
                <ul class="navbar-nav header-right">
                    <!-- <li class="nav-item">
                        <div class="input-group search-area d-lg-inline-flex d-none">
                            <div class="input-group-append">
                                <span class="input-group-text"><a href="javascript:void(0)"><i class="flaticon-381-search-2"></i></a></span>
                            </div>
                            <input type="text" class="form-control" placeholder="Search here...">
                        </div>
                    </li>
                    <li class="nav-item dropdown notification_dropdown">
                        <a class="nav-link bell bell-link" href="javascript:void(0)">
                            <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M2.23779 10.2492L4.66679 11.7064V8.30554L2.23779 10.2492Z" fill="#67636D"/>
                                <path d="M1.1665 12.327V23.3334C1.16852 23.8531 1.28817 24.3656 1.5165 24.8325L9.20134 17.15L1.1665 12.327Z" fill="#67636D"/>
                                <path d="M26.4832 24.8325C26.7115 24.3656 26.8311 23.8531 26.8332 23.3334V12.327L18.7983 17.15L26.4832 24.8325Z" fill="#67636D"/>
                                <path d="M23.3335 8.30554V11.7064L25.7625 10.2492L23.3335 8.30554Z" fill="#67636D"/>
                                <path d="M21.0492 13.0772C21.024 12.998 21.0076 12.9162 21.0002 12.8334V7.00004C21.0002 6.69062 20.8773 6.39388 20.6585 6.17508C20.4397 5.95629 20.1429 5.83337 19.8335 5.83337H8.16684C7.85742 5.83337 7.56067 5.95629 7.34188 6.17508C7.12309 6.39388 7.00017 6.69062 7.00017 7.00004V12.8334C6.99274 12.9162 6.97631 12.998 6.95117 13.0772L14.0002 17.3064L21.0492 13.0772Z" fill="#67636D"/>
                                <path d="M17.3262 3.50003L14.7292 1.4222C14.5222 1.25653 14.2651 1.16626 14 1.16626C13.7349 1.16626 13.4777 1.25653 13.2708 1.4222L10.6738 3.50003H17.3262Z" fill="#67636D"/>
                                <path d="M16.7358 18.3855L14.6008 19.6688C14.4194 19.7778 14.2117 19.8354 14 19.8354C13.7883 19.8354 13.5806 19.7778 13.3991 19.6688L11.2641 18.3855L3.16748 26.4833C3.63438 26.7117 4.14691 26.8313 4.66665 26.8333H23.3333C23.853 26.8313 24.3656 26.7117 24.8325 26.4833L16.7358 18.3855Z" fill="#67636D"/>
                            </svg>
                            <span class="badge text-white badge-primary rounded-circle">6</span>
                        </a>
                    </li>
                    <li class="nav-item dropdown notification_dropdown">
                        <a class="nav-link  ai-icon" href="javascript:void(0)" role="button" data-bs-toggle="dropdown">
                            <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M23.3333 19.8333H23.1187C23.2568 19.4597 23.3295 19.065 23.3333 18.6666V12.8333C23.3294 10.7663 22.6402 8.75902 21.3735 7.12565C20.1068 5.49228 18.3343 4.32508 16.3333 3.80679V3.49996C16.3333 2.88112 16.0875 2.28763 15.6499 1.85004C15.2123 1.41246 14.6188 1.16663 14 1.16663C13.3812 1.16663 12.7877 1.41246 12.3501 1.85004C11.9125 2.28763 11.6667 2.88112 11.6667 3.49996V3.80679C9.66574 4.32508 7.89317 5.49228 6.6265 7.12565C5.35983 8.75902 4.67058 10.7663 4.66667 12.8333V18.6666C4.67053 19.065 4.74316 19.4597 4.88133 19.8333H4.66667C4.35725 19.8333 4.0605 19.9562 3.84171 20.175C3.62292 20.3938 3.5 20.6905 3.5 21C3.5 21.3094 3.62292 21.6061 3.84171 21.8249C4.0605 22.0437 4.35725 22.1666 4.66667 22.1666H23.3333C23.6428 22.1666 23.9395 22.0437 24.1583 21.8249C24.3771 21.6061 24.5 21.3094 24.5 21C24.5 20.6905 24.3771 20.3938 24.1583 20.175C23.9395 19.9562 23.6428 19.8333 23.3333 19.8333Z" fill="#67636D"/>
                                <path d="M9.98193 24.5C10.3863 25.2088 10.971 25.7981 11.6767 26.2079C12.3823 26.6178 13.1839 26.8337 13.9999 26.8337C14.816 26.8337 15.6175 26.6178 16.3232 26.2079C17.0289 25.7981 17.6136 25.2088 18.0179 24.5H9.98193Z" fill="#67636D"/>
                            </svg>
                            <span class="badge text-white badge-primary rounded-circle">4</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <div id="dlab_W_Notification1" class="widget-media dlab-scroll p-3 height380">
                                <ul class="timeline">
                                    <li>
                                        <div class="timeline-panel">
                                            <div class="media me-2">
                                                <img alt="image" width="50" src="{% static 'vora/images/avatar/1.jpg' %}">
                                            </div>
                                            <div class="media-body">
                                                <h6 class="mb-1">Dr sultads Send you Photo</h6>
                                                <small class="d-block">29 July 2020 - 02:26 PM</small>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="timeline-panel">
                                            <div class="media me-2 media-info">
                                                KG
                                            </div>
                                            <div class="media-body">
                                                <h6 class="mb-1">Resport created successfully</h6>
                                                <small class="d-block">29 July 2020 - 02:26 PM</small>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="timeline-panel">
                                            <div class="media me-2 media-success">
                                                <i class="fa fa-home"></i>
                                            </div>
                                            <div class="media-body">
                                                <h6 class="mb-1">Reminder : Treatment Time!</h6>
                                                <small class="d-block">29 July 2020 - 02:26 PM</small>
                                            </div>
                                        </div>
                                    </li>
                                     <li>
                                        <div class="timeline-panel">
                                            <div class="media me-2">
                                                <img alt="image" width="50" src="{% static 'vora/images/avatar/1.jpg' %}">
                                            </div>
                                            <div class="media-body">
                                                <h6 class="mb-1">Dr sultads Send you Photo</h6>
                                                <small class="d-block">29 July 2020 - 02:26 PM</small>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="timeline-panel">
                                            <div class="media me-2 media-danger">
                                                KG
                                            </div>
                                            <div class="media-body">
                                                <h6 class="mb-1">Resport created successfully</h6>
                                                <small class="d-block">29 July 2020 - 02:26 PM</small>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="timeline-panel">
                                            <div class="media me-2 media-primary">
                                                <i class="fa fa-home"></i>
                                            </div>
                                            <div class="media-body">
                                                <h6 class="mb-1">Reminder : Treatment Time!</h6>
                                                <small class="d-block">29 July 2020 - 02:26 PM</small>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <a class="all-notification" href="javascript:void(0)">See all notifications <i class="ti-arrow-right"></i></a>
                        </div>
                    </li> -->
                    <li class="nav-item dropdown header-profile">
                        <a class="nav-link" href="javascript:void(0)" role="button" data-bs-toggle="dropdown" style="border:none !important;">
                            <img src="/media/{{ request.user.avatar }}" width="20" alt=""/>
                            <div class="header-info">
                                {% if request.user.is_authenticated %}
                                    <span class="text-black">{{ request.user.first_name }} {{ request.user.last_name }} </span>
                                    <p class="fs-12 mb-0">
                                        {% for g in request.user.groups.all %}
                                            {{ g.name }}
                                        {% endfor %}
                                    </p>
                                {% endif %}
                            </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <!-- <a href="{% url 'vora:app-profile' %}" class="dropdown-item ai-icon">
                                <svg id="icon-user1" xmlns="http://www.w3.org/2000/svg" class="text-primary" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                <span class="ms-2">Profile </span>
                            </a>
                            <a href="{% url 'vora:email-inbox' %}" class="dropdown-item ai-icon">
                                <svg id="icon-inbox" xmlns="http://www.w3.org/2000/svg" class="text-success" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
                                <span class="ms-2">Inbox </span>
                            </a> -->
                            <a href="{% url 'vora:logout' %}" class="dropdown-item ai-icon">
                                <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" class="text-danger" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
                                <span class="ms-2">Logout </span>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

dashboard/templates/vora/elements/nav-header.html
{% load static %}
<div class="nav-header">
    <a href="{% url 'vora:index' %}" class="brand-logo">
        <div class="logo-abbr">
        <img class="logo-compact" style="display: block!important;" src="{% static 'vora/images/logo.png' %}" alt="">

        </div>
        <div class="brand-title">
        </div>
    </a>

    <div class="nav-control">
        <div class="hamburger">
            <span class="line"></span><span class="line"></span><span class="line"></span>
        </div>
    </div>
</div>

dashboard/templates/vora/elements/sidebar.html
{% load static %}
<div class="dlabnav">
    <div class="dlabnav-scroll">
        <ul class="metismenu" id="menu">
            <li><a class="" href="{% url 'vora:index' %}" >
                <i class="flaticon-381-networking"></i>
                <span class="nav-text">Dashboard</span>
            </a>
        </li>
                <li><a class="has-arrow ai-icon" href="javascript:void(0);" aria-expanded="false">
                    <i class="flaticon-381-networking"></i>
                    <span class="nav-text">Customers</span>
                </a>
                <ul aria-expanded="false">
                    
                    <li><a href="{% url 'vora:customers' %}">Active Customers</a></li>
                    <li class="d-none"><a href="{% url 'vora:inactiveCustomers' %}" >Inactive Customers</a></li>
                    
                </ul>
            </li>
            
            <li><a class="has-arrow ai-icon" href="javascript:void(0);" aria-expanded="false">
                    <i class="flaticon-381-networking"></i>
                    <span class="nav-text">Master</span>
                </a>
                <ul aria-expanded="false">
                      <li><a href="{% url 'vora:category' %}">Category</a></li>
                      <li><a href="{% url 'vora:sub-category' %}">Sub Category</a></li>
                      <li><a href="{% url 'vora:tax' %}">Tax</a></li>
                      <li><a href="{% url 'vora:industry-filter' %}">Industry</a></li>
                      <li><a href="{% url 'vora:interest-area' %}">Interest Area</a></li>
                </ul>
            </li>

            <li><a class="has-arrow ai-icon" href="javascript:void(0);" aria-expanded="false">
                    <i class="flaticon-381-networking"></i>
                    <span class="nav-text">Solutions</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'vora:solutions' %}">All Solutions</a></li>
                    <li><a href="{% url 'vora:archieved-solutions' %}">Archieved Solutions</a></li>
                </ul>
            </li>
            <li>
                <a class="has-arrow ai-icon" href="javascript:void(0);" aria-expanded="false">
                    <i class="flaticon-381-networking"></i>
                    <span class="nav-text">Orders</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'vora:all-orders' %}">All Orders</a></li>
                    <li><a href="{% url 'vora:all-active-orders' %}">Active Orders</a></li>
                    <li><a href="{% url 'vora:all-draft-orders' %}">Draft Orders</a></li>
                    <li><a href="{% url 'vora:all-complete-orders' %}">Complete Orders</a></li>
                </ul>
            </li>

            {% if perms.users.view_customuser or perms.auth.view_group or perms.auth.view_permission %}
                <li><a class="has-arrow ai-icon" href="javascript:void(0);" aria-expanded="false">
                    <i class="flaticon-381-networking"></i>
                    <span class="nav-text">Admin Users</span>
                    
                </a>
                <ul aria-expanded="false">
                    {% if perms.users.view_customuser or perms.users.change_customuser or perms.users.add_customuser or perms.users.delete_customuser %}
                    <li><a href="{% url 'vora:users' %}">Users</a></li>
                    {% endif %}
                    {% if perms.auth.view_group or perms.auth.change_group or perms.auth.add_group or perms.auth.delete_group %}
                    <li><a href="{% url 'vora:groups' %}">Roles</a></li>
                    {% endif %}
                    {% if perms.auth.view_permission or perms.auth.change_permission or perms.auth.add_permission or  perms.auth.delete_permission%}
                    <li><a href="{% url 'vora:permissions' %}" class="d-none">Permissions</a></li>
                    {% endif %}
                </ul>
            </li>
            {% endif %}
            
        </ul>
        <a class="add-menu-sidebar  d-none" href="javascript:void(0)"  data-bs-toggle="modal" data-bs-target="#addOrderModalside" >+ New Project</a>
        <div class="copyright">
            <p><strong>FloorWalk Admin Dashboard</strong> © 2023 All Rights Reserved</p>
        </div>
    </div>
</div>